version: "3.9"
services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    # Choose your port here, default is 3000
      - "3000:25565"
    environment:
      MC_VERSION: 1.20.1
      MC_RAM: 4
    volumes:
      - .:/app/
    stdin_open: true
    tty: true